package com.neuedu.dao;

import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer userId,Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */

    List<Order> select();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    Order findOrderByOrderNo(@Param("orderNo") Long orderNo);

    int updateBystatusandpayment(@Param("order") Order order);

    /**
     * 根据订单号和用户名查询订单明细
     * */
    List<Order> findOrderItemByOrderNoAnduserId(Integer userId,Long orderNo);
    List<Order> findOrderItem(Long orderNo);
    /**
     * 根据订单号进行发货
     * */
  int updateByuserIdAndOrderNo(Long orderNo);
    /**
     * 查找未支付订单
    * */
    List<Order> selectnopay(Integer userId);
    /**
     * 后台查找未支付订单
     * */
    List<Order>nopay();
    /**
     * 查找支付订单
     * */
    List<Order> selectpay(Integer userId);
    /**
     * 后台查找支付订单
     * */
    List<Order> pay();
    // 查找全部订单
    List<Order> allorder(Integer userId);
    // 后台查找全部订单
    List<Order> manageallorder();
    //查找已发货订单
    List<Order> send(Integer userId);
    //查找已发货订单
    List<Order> yes();
    Order findOrderByUseridAndOrderNo(@Param("userId") Integer userId,@Param("orderNo") Long orderNo);
    //删除订单
    int deles(@Param("productList") List<Long> productList);
}