package com.neuedu.dao;

import com.neuedu.pojo.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order_item
     *
     * @mbg.generated
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order_item
     *
     * @mbg.generated
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order_item
     *
     * @mbg.generated
     */
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderItem record);
    /**
     * 批量插入
     * */
    int insertBatch(@Param("orderItemList") List<OrderItem> orderItemList);

    /**
     * 根据订单号查询订单明细
     * */
    List<OrderItem> findOrderItemByOrderNo(@Param(("orderNo")) Long orderNo);


    /**
     * 根据订单号和用户名查询订单明细
     * */
    List<OrderItem> findOrderItemByOrderNoAnduserId(Integer userId,Long orderNo);
    List<OrderItem> findOrderItem(Long orderNo);
    //删除订单
    int deles(@Param("productList") List<Long> productList);
}