package com.neuedu.dao;

import com.neuedu.common.ServerResponse;
import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    UserInfo select(@Param("userInfo") UserInfo userInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    int updateByKey(@Param("userInfo")UserInfo userInfo);
    /**
     * 判断用户名是否存在
     * */
    int isexitsname(@Param("username") String username);

    /**
     * 判断邮箱是否存在
     * */
    int isexitsemail(@Param("email") String email);
    /**
     * 根据用户名和密码查询
     * */
    UserInfo finduserbynameandpwd(@Param("username") String username,@Param("password") String password);
    /**
     * 根据username密保问题
     * */
    public String forget_get_question(@Param("username") String username);
    /**
     * 提交答案
     * */
    public int forget_check_answer(@Param("username") String username,
                                   @Param("question") String question,@Param("answer") String answer);
    /**
     * 修改密码
     * */
    public int forget_reset_password(@Param("username") String username,
                                     @Param("password") String newpassword);
    /**
     * 修改用户信息
     * */
    public int updateUser(@Param("userInfo") UserInfo userInfo);
}