
server:
  port: 8888
  servlet:
    context-path: /

limit:
  minMoney: 2
  maxMoney: 100
  desc: 最低${limit.minMoney}最高${limit.maxMoney}
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        max-active: 20
        max-wait: 6000
        min-idle: 1
        test-on-borrow: true
        test-on-return: true
  thymeleaf:
    mode: HTML5
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: file:f:/upload/

business:
  imageHost: http://img.cdn.imbession.top/
  qrHost: http://localhost:8888/static/qrcode/
shopping:
  image: http://localhost/
mybatis:
      mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
      config-location: classpath:mybatis-config.xml
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: countSql
logging:
  level:
    com.neuedu.dao: debug
